import { useEffect, useState } from 'react'
import { CardHeader, PageIntro, SectionCard } from '../components/PageComponents'

const dayNames = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN']
const palette = ['mint', 'pink', 'cyan', 'yellow', 'orange', 'blue']
const names = ['IELTS KCD', 'LỚP 11', 'LỚP 12', 'LỚP 3', 'IELTS 11', 'LỚP 9']
const times = ['14:00', '15:30', '17:30', '19:00']
const viewOptions = [['day', 'Ngày'], ['week', 'Tuần'], ['month', 'Tháng'], ['year', 'Năm']]
const keyOf = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
const startOfWeek = (date) => { const copy = new Date(date); const offset = (copy.getDay() + 6) % 7; copy.setDate(copy.getDate() - offset); copy.setHours(0, 0, 0, 0); return copy }
const monthLabel = (date) => date.toLocaleDateString('vi-VN', { month: 'long', year: 'numeric' }).replace(/^tháng/i, 'Tháng')
const fullDateLabel = (date) => date.toLocaleDateString('vi-VN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
const timeValue = (time) => time.length === 5 ? time : `${time}:00`
const seedEvents = () => Object.fromEntries(Array.from({ length: 30 }, (_, i) => { const date = i + 1; const count = date % 7 === 0 ? 4 : date === 29 ? 1 : 3; return [`2026-09-${String(date).padStart(2, '0')}`, Array.from({ length: count }, (_, j) => { const start = times[(date + j) % times.length]; return { id: `seed-${date}-${j}`, title: names[(date + j) % names.length], start, end: start === '19:00' ? '20:30' : `${String(Number(start.slice(0, 2)) + 1).padStart(2, '0')}:30`, tone: palette[(date + j) % palette.length] } })] }))
function EventPill({ event, compact = false, onRemove }) { const height = Math.max(36, (minutes(event.end) - minutes(event.start)) / 60 * 65 - 8); return <div className={`event-pill ${event.tone} ${compact ? 'compact-pill' : ''}`} style={{ minHeight: `${height}px` }}><b>{event.title}</b><span>{event.start}–{event.end}</span>{onRemove && <button className="event-remove" onClick={(e) => { e.stopPropagation(); onRemove() }}>×</button>}</div> }
const minutes = (value) => { const [h, m] = value.split(':').map(Number); return h * 60 + m }

export default function SchedulePage() {
  const [view, setView] = useState('month'); const [anchor, setAnchor] = useState(() => new Date()); const [eventMap, setEventMap] = useState(() => { try { return JSON.parse(localStorage.getItem('nhip-hoc-events')) || seedEvents() } catch { return seedEvents() } }); const [deadlines, setDeadlines] = useState(() => JSON.parse(localStorage.getItem('nhip-hoc-deadlines') || '[]')); const [composer, setComposer] = useState(false); const [selectedDate, setSelectedDate] = useState(null); const [deadlineMode, setDeadlineMode] = useState(false); const [draft, setDraft] = useState({ title: '', date: keyOf(anchor), start: '14:00', end: '15:30', tone: 'blue' })
  useEffect(() => { localStorage.setItem('nhip-hoc-events', JSON.stringify(eventMap)) }, [eventMap])
  useEffect(() => { localStorage.setItem('nhip-hoc-deadlines', JSON.stringify(deadlines)) }, [deadlines])
  const totalSessions = Object.values(eventMap).reduce((sum, day) => sum + day.length, 0)
  const visibleTitle = view === 'year' ? String(anchor.getFullYear()) : view === 'day' ? fullDateLabel(anchor) : view === 'week' ? `${fullDateLabel(startOfWeek(anchor))} – ${fullDateLabel(new Date(startOfWeek(anchor).getTime() + 6 * 86400000))}` : monthLabel(anchor)
  const openComposer = (date = anchor, hour = '14:00', deadline = false) => { setDeadlineMode(deadline); const end = `${String(Number(hour.slice(0, 2)) + 1).padStart(2, '0')}:30`; setDraft({ title: '', date: keyOf(date), start: hour, end, tone: 'blue' }); setComposer(true) }
  const move = (amount) => { const next = new Date(anchor); if (view === 'day') next.setDate(next.getDate() + amount); else if (view === 'week') next.setDate(next.getDate() + amount * 7); else if (view === 'month') next.setMonth(next.getMonth() + amount); else next.setFullYear(next.getFullYear() + amount); setAnchor(next) }
  const saveEvent = () => { if (!draft.title.trim()) return; const item = { ...draft, id: `custom-${Date.now()}` }; deadlineMode ? setDeadlines((current) => [...current, item]) : setEventMap((current) => ({ ...current, [draft.date]: [...(current[draft.date] || []), item] })); setComposer(false) }
  return <>
    <PageIntro eyebrow="LỊCH HỌC & DEADLINE" title="Lịch học của bạn" subtitle="Chọn ngày, tuần, tháng hoặc năm để audit lịch theo đúng góc nhìn cần thiết."><div className="intro-actions"><button className="primary-button" onClick={() => openComposer()}>＋ Thêm lịch</button><button className="success-button" onClick={() => openComposer(anchor, '14:00', true)}>▣ + Deadline</button></div></PageIntro>
    <div className="summary-grid schedule-stats"><div className="summary-chip blue"><span>TỔNG BUỔI</span><b>{totalSessions}</b><i>▥</i></div><div className="summary-chip mint"><span>TỔNG GIỜ</span><b>234.0</b><i>◷</i></div><div className="summary-chip gold"><span>DEADLINE SẮP TỚI</span><b>4 bài</b><i>☷</i></div><div className="summary-chip coral"><span>TIẾN ĐỘ THÁNG</span><b>68%</b><i>↗</i></div></div>
    <SectionCard className="calendar-card"><div className="calendar-toolbar"><div className="calendar-nav"><button className="today-button" onClick={() => setAnchor(new Date())}>Hôm nay</button><button className="round-button" aria-label="Lùi thời gian" onClick={() => move(-1)}>‹</button><button className="round-button" aria-label="Tiến thời gian" onClick={() => move(1)}>›</button><strong>{visibleTitle}</strong></div><div className="view-switcher" role="tablist">{viewOptions.map(([value, label]) => <button key={value} className={view === value ? 'active' : ''} onClick={() => setView(value)} role="tab" aria-selected={view === value}>{label}</button>)}</div></div>{view === 'month' && <MonthView anchor={anchor} eventMap={eventMap} onSelect={setSelectedDate} />}{view === 'week' && <WeekView anchor={anchor} eventMap={eventMap} onAdd={openComposer} onRemove={(date, id) => setEventMap((current) => ({ ...current, [date]: current[date].filter((item) => item.id !== id) }))} />}{view === 'day' && <DayView anchor={anchor} eventMap={eventMap} onAdd={openComposer} onRemove={(date, id) => setEventMap((current) => ({ ...current, [date]: current[date].filter((item) => item.id !== id) }))} />}{view === 'year' && <YearView anchor={anchor} eventMap={eventMap} onSelect={(date) => { setAnchor(date); setView('month') }} />}</SectionCard>
    <div className="schedule-bottom"><SectionCard className="deadline-card"><CardHeader icon="◷" title="Deadline sắp tới" tone="orange" action="Thêm" onAction={() => openComposer(anchor, '14:00', true)} /><div className="deadline-list"><div className="deadline-item urgent"><span className="deadline-date">28<br /><small>THÁNG 9</small></span><div><b>Nộp bài Reading IELTS</b><small>Còn 2 ngày · ưu tiên cao</small></div><button className="deadline-remove" onClick={(e) => e.currentTarget.closest('.deadline-item').remove()}>×</button></div><div className="deadline-item"><span className="deadline-date">30<br /><small>THÁNG 9</small></span><div><b>Ôn tập từ vựng tuần 4</b><small>Còn 4 ngày</small></div><button className="deadline-remove" onClick={(e) => e.currentTarget.closest('.deadline-item').remove()}>×</button></div></div></SectionCard><SectionCard className="audit-card"><CardHeader icon="⌁" title="Tổng quan nhanh" tone="mint" /><div className="audit-line"><span>Buổi đã hoàn thành</span><b>21 / 31</b></div><div className="audit-progress"><i style={{ width: '68%' }} /></div><div className="audit-line"><span>Ngày có lịch học</span><b>25 ngày</b></div><button className="outline-button full-button">Xem báo cáo tháng</button></SectionCard></div>
    {selectedDate && <div className="composer-backdrop" onMouseDown={() => setSelectedDate(null)}><div className="day-popup" onMouseDown={(event) => event.stopPropagation()}><div className="composer-top"><b>{fullDateLabel(selectedDate)}</b><button onClick={() => setSelectedDate(null)}>×</button></div>{(eventMap[keyOf(selectedDate)] || []).map((event) => <div className="popup-event" key={event.id}><EventPill event={event} /><button onClick={() => setEventMap((current) => ({ ...current, [keyOf(selectedDate)]: current[keyOf(selectedDate)].filter((item) => item.id !== event.id) }))}>×</button></div>)}<button className="primary-button" onClick={() => { setSelectedDate(null); openComposer(selectedDate) }}>＋ Thêm lịch</button></div></div>}
    {composer && <EventComposer draft={draft} setDraft={setDraft} onClose={() => setComposer(false)} onSave={saveEvent} />}
  </>
}
function MonthView({ anchor, eventMap, onSelect }) { const todayKey = keyOf(new Date()); const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const start = new Date(first); start.setDate(1 - ((first.getDay() + 6) % 7)); return <div className="month-calendar"><div className="weekday-row">{dayNames.map((day) => <b key={day}>{day}</b>)}</div><div className="month-grid">{Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); const items = eventMap[keyOf(date)] || []; const current = date.getMonth() === anchor.getMonth(); return <button className={`month-cell ${current ? '' : 'muted-cell'} ${keyOf(date) === todayKey ? 'selected-date' : ''}`} key={keyOf(date)} onClick={() => onSelect(date)}><div className="date-number">{date.getDate()}</div><div className="event-list">{items.slice(0, 3).map((event) => <EventPill event={event} key={event.id} />)}{items.length > 3 && <small>+{items.length - 3} buổi khác</small>}</div></button> })}</div></div> }
function WeekView({ anchor, eventMap, onAdd, onRemove }) { const start = startOfWeek(anchor); return <div className="time-grid"><div className="time-head"><span />{Array.from({ length: 7 }, (_, i) => { const date = new Date(start); date.setDate(start.getDate() + i); return <b key={keyOf(date)}>{dayNames[i]}<small>{date.getDate()}</small></b> })}</div>{Array.from({ length: 15 }, (_, i) => { const hour = i + 7; return <div className="time-row" key={hour}><span>{String(hour).padStart(2, '0')}:00</span>{Array.from({ length: 7 }, (_, day) => { const date = new Date(start); date.setDate(start.getDate() + day); const items = (eventMap[keyOf(date)] || []).filter((event) => Number(event.start.slice(0, 2)) === hour); return <button key={day} onClick={() => onAdd(date, `${String(hour).padStart(2, '0')}:00`)}>{items.map((event) => <EventPill event={event} compact key={event.id} onRemove={() => onRemove(keyOf(date), event.id)} />)}</button> })}</div> })}</div> }
function DayView({ anchor, eventMap, onAdd, onRemove }) { const items = eventMap[keyOf(anchor)] || []; return <div className="day-view"><div className="day-view-head"><b>{fullDateLabel(anchor)}</b><span>{items.length} sự kiện · bấm vào khung giờ để thêm</span></div>{Array.from({ length: 15 }, (_, i) => { const hour = i + 7; const hourItems = items.filter((event) => Number(event.start.slice(0, 2)) === hour); return <button className="day-slot" key={hour} onClick={() => onAdd(anchor, `${String(hour).padStart(2, '0')}:00`)}><span>{String(hour).padStart(2, '0')}:00</span><div>{hourItems.map((event) => <EventPill event={event} key={event.id} onRemove={() => onRemove(keyOf(anchor), event.id)} />)}</div></button> })}</div> }
function YearView({ anchor, eventMap, onSelect }) { return <div className="year-grid">{Array.from({ length: 12 }, (_, month) => { const date = new Date(anchor.getFullYear(), month, 1); const days = new Date(anchor.getFullYear(), month + 1, 0).getDate(); return <button className="year-month" key={month} onClick={() => onSelect(date)}><b>{date.toLocaleDateString('vi-VN', { month: 'long' })}</b><div className="mini-week">{dayNames.map((day) => <span key={day}>{day.slice(1)}</span>)}</div><div className="mini-days">{Array.from({ length: days }, (_, day) => { const key = keyOf(new Date(anchor.getFullYear(), month, day + 1)); return <i className={(eventMap[key] || []).length ? 'has-events' : ''} key={day}>{day + 1}</i> })}</div></button> })}</div> }
function EventComposer({ draft, setDraft, onClose, onSave }) { return <div className="composer-backdrop" onMouseDown={onClose}><form className="event-composer" onSubmit={(event) => { event.preventDefault(); onSave() }} onMouseDown={(event) => event.stopPropagation()}><div className="composer-top"><b>Thêm sự kiện</b><button type="button" onClick={onClose}>×</button></div><input autoFocus required placeholder="Tên sự kiện hoặc lớp học" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /><label>Ngày<input type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} /></label><div className="composer-times"><label>Bắt đầu<input type="time" value={timeValue(draft.start)} onChange={(event) => setDraft({ ...draft, start: event.target.value })} /></label><label>Kết thúc<input type="time" value={timeValue(draft.end)} onChange={(event) => setDraft({ ...draft, end: event.target.value })} /></label></div><label>Màu lịch<select value={draft.tone} onChange={(event) => setDraft({ ...draft, tone: event.target.value })}>{palette.map((tone) => <option key={tone} value={tone}>{tone}</option>)}</select></label><div className="composer-actions"><button type="button" className="ghost-button" onClick={onClose}>Hủy</button><button className="primary-button" type="submit">Lưu lịch</button></div></form></div> }
